<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions name="TestService" 
	targetNamespace="http://xmlns.frank-rahn.de/ws/testservice/1.0"
	xmlns:test="http://xmlns.frank-rahn.de/types/testtypes/1.0" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="http://xmlns.frank-rahn.de/types/testtypes/1.0" 
				schemaLocation="testtypes.xsd" />
		</xsd:schema>
	</wsdl:types>
	
</wsdl:definitions>